# Generated by Django 4.1.7 on 2024-04-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=248)),
                ("ask_price", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("B", "Books"),
                            ("Elec", "Electronics"),
                            ("H&K", "Home & Kitchen"),
                            ("C", "Clothing"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("comments", models.CharField(max_length=248)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auctions.listing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bidding",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("bid_price", models.IntegerField()),
                ("number_of_item", models.IntegerField()),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auctions.listing",
                    ),
                ),
            ],
        ),
    ]
