# Generated by Django 4.1.7 on 2024-05-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing_alter_user_id_watchlist_listing_owner_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="winners",
            new_name="winner",
        ),
        migrations.AddField(
            model_name="listing",
            name="winning_bid",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    (" ", "Others"),
                    ("T", "Toys"),
                    ("Clo", "Clothing"),
                    ("H&K", "Home & Kitchen"),
                    ("B", "Books"),
                    ("Elec", "Electronics"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="listing",
            name="imagelink",
            field=models.CharField(
                blank=True, default=False, max_length=128, null=True
            ),
        ),
    ]
