# Generated by Django 4.1.7 on 2024-04-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_bidding_user_comment_user_listing_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidding",
            name="user",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("Clo", "Clothing"),
                    ("H&K", "Home & Kitchen"),
                    ("Elec", "Electronics"),
                    ("B", "Books"),
                    ("T", "Toys"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="owner",
            field=models.CharField(max_length=64),
        ),
    ]
