# Generated by Django 4.1.7 on 2024-04-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_bidding_user_alter_comment_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("H&K", "Home & Kitchen"),
                    ("Elec", "Electronics"),
                    ("B", "Books"),
                    ("Clo", "Clothing"),
                    ("T", "Toys"),
                ],
                max_length=5,
                null=True,
            ),
        ),
    ]
