# Generated by Django 4.1.7 on 2024-04-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_alter_listing_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="imagelink",
            field=models.CharField(default=False, max_length=128),
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("Clo", "Clothing"),
                    ("Elec", "Electronics"),
                    ("H&K", "Home & Kitchen"),
                    ("B", "Books"),
                    ("T", "Toys"),
                ],
                max_length=5,
                null=True,
            ),
        ),
    ]
